= cljdoc Developer Technical Guide

== Introduction

So you'd like to contribute your development skills to cljdoc itself? This is great!

You'll first want to read link:../CONTRIBUTING.adoc[Contributing] and familiarize yourself with
the link:CODE_OF_CONDUCT.adoc[Code of Conduct].

This document is a collection of technical notes that should be useful to a cljdoc developer.
If you find there is something missing from this doc that stumped you, we would greatly
appreciate you letting us know.

== Related developer docs
You can learn how to setup a local development environment in link:running-cljdoc-locally.adoc[Running cljdoc locally].

Being aware of how to diagnose and fix analysis job builds will also be of use, see link:fixing-builds.md[fixing cljdoc builds].

[[system-overview]]
== System Overview

You'll find a detailed deployment description of cljdoc under the link:../ops[ops directory] but here is
what cljdoc looks like in production in broad strokes:

image::system-overview.svg[]

A library author publishes to clojars. When the cljdoc analysis service
discovers the new library, it initiates two tasks:

. it launches an api analysis job on circleci
. clones the library's project from github for library docs, info and file mappings.

The results of the analysis tasks are then stored in an internal cljdoc database.
The cljdoc web site then draws on this database to present library docs to cljdoc users.

Note that while most Clojure developers host their source on github, gitlab and
bitbucket are also supported source code repositories.

== Database Overview

=== SQLite

Cljdoc makes use of two https://sqlite.org[SQLite] databases.
The schemas are small and simple.

Some data is stored in nippy blobs.
Nippy is fast and stores data compactly, but makes data opaque when viewing a raw database.
This little database overview diagram should help.

image::database-overview.svg[]

Historical notes:

* `builds.error_info` is obsolete.
** It stored a nippy blob of the exception object
** It is replaced by `builds.error_info_map`, which stores a nippy blob of a map representation of the exception

Tips:

* You'll find the SQLite databases under the `data` dir.
* Using more modern features of SQLite can be problematic.
Features such as renaming a column, for example.
Cljdoc developers often use MacOS, and it bundles an older version of SQLite.
* You might find a tools such as the  https://sqlitebrowser.org/[DB Browser for SQLite] useful.
* It can sometimes be useful to work locally with a backup of the production databases.
Reach out on Slack if you think this would be helpful to you.

=== Lucene

Cljdoc supports full text querying for libraries with a https://lucene.apache.org/[Lucene] index.

The Lucene index allows cljdoc users to search all available libraries, not necessarily just the ones cljdoc has already built docs for. Available libraries are automatically sourced from:

* Clojars via `\https://clojars.org/repo/feed.clj.gz` daily, and updates by the minute via the `\https://clojars.org/search` API.
* Maven Central via `\http://search.maven.org` APIs.
Not many Clojurians host on Maven Central but, quite notably, the Clojure core team does.
We only fetch for a list of explicit group-ids and are happy to update this list on request.

At the time of this writing we index:

* `group-id` & `artifact-id` - we also store an exact untokenized version of these to support exact matches
* `blurb` - a shortened description from the library's pom
* `origin` - either `clojars` or `maven-central` (not currently searched but presented)
* `versions` - a list of all available library versions is stored unindexed, we present available library versions in various spots throughout the cljdoc web site.

At index time, we incorporate clojars download stats, stored in our SQLite `clojars_stats` table, as popularity ranking.

Lucene is powerful, fast and widely used.
It can also be a bit overwhelming to wade through its many features and options, many of which have evolved over decades.

Tips

* You'll find the Lucene index under `data/index-lucene-{some identifiter}`.
Feel free to change `{some-identifier}` when making an incompatible change to the Lucene index.
(As of this writing specified under `index-dir` in the `cljdoc.server.system` ns).
Lucene will simply create a fresh new index.
* Luke is a useful tool to take a peek at your Lucene index.
Download https://lucene.apache.org/core/downloads.html[a full Lucene binary release], unpack it and then launch luke via the `bin/luke.sh` script.

== Conventions

=== Diagrams

To make diagramming accessible to anyone who wants to add or modify an image in
cljdoc's documentation, we are using the very capable and free to use
https://www.draw.io/[draw.io]. We commit the `.drawio` image along with the web
renderable version of the image in the cljdoc github repository.

For example, this document references `system-overview.svg` and we include
alongside, in the same directory, the draw.io source `system-overview.drawio`.

To make things easy to find, images should sit in the same directory as the doc.

=== Linting

We use https://github.com/borkdude/clj-kondo[clj-kondo] to help catch common
coding errors early. The build server will fail the build if any lint errors are
found. To find lint errors it runs `script/lint.sh` and so can you!

Note that clj-kondo really shines when you
https://github.com/borkdude/clj-kondo/blob/master/doc/editor-integration.md[integrate
it with your development environment].

=== Coding style

We try to follow https://guide.clojure.style[The Clojure Style Guide].

We use https://github.com/weavejester/cljfmt[cljfmt] check for any code formatting problems.
The build server will fail the build if any formatting issues are detected.
To check for issues it runs `script/code-format.sh check` and so can you!

You can also run `script/code-format.sh fix` to have cljfmt fix any code formatting issues it has detected.

=== Outdated dependencies

Carefully applying available updates keeps up with security patches and reduces the overall maintenance burden.

To check for outdated Clojure and JavaScript dependencies run `bb script/outdated.clj`.
