#!/usr/bin/env bash

cmd="$1"

# Probably should be using getopts here or something ¯\_(ツ)_/¯

if [[ "$cmd" == "build" ]]; then
    project="$2"
    version="$3"

    if [[ "$project" == *\/* ]]; then
        group=$(echo $project | sed 's/\/.*//' | tr . /)
        artifact=$(echo $project | sed 's/^[^/]*\///')
    else
        echo "Parse project"
        group=$(echo "$project" | tr . /)
        artifact="$project"
    fi

    echo -e "Group: $group\nArtifact: $artifact\nVersion: $version\n"

    curl \
      -d project="$project" \
      -d version="$version" \
      -i https://cljdoc.xyz/api/request-build2

else
    echo "Usage:"
    echo "  cljdoc build bidi 2.1.3"
    echo "  cljdoc build confetti/s3-deploy 0.1.2"
fi
